### ISSUE TITLE
Can the patched file size be reduced?

### ISSUE THREAD

**Issue by mehQQ** [lunixbochs/patchkit#11] opened 2017-03-28 15:47 UTC
Hi. I was trying to patch some binaries and found that the binary became much bigger after patched. For example, a 15KB file become 2.1MB (139 times bigger). If we only need to inject few codes, can the size be reduced? Cause for small binaries, this seems a bit unaffordable ...
Thanks.

**Comment by lunixbochs** [comment] 2017-03-28 16:10
Duplicate of #4.

This is a problem with the elf repacking to work around issues with some elf loaders while expanding the program header table. I'll check back into this.

**Comment by lunixbochs** [comment] 2017-03-28 16:43
The problem lies when patching a huge page binary. I need to add 1-3 patch segments (text `R-X`, data `RW-`, jit `RWX`). This won't fit in the existing program header space, and GNU ld.so seems to barf if I move the PHDR out of the text segment, and I can't shift the text segment without messing up alignment, so I currently move the PHDR to the end of the text segment.

GNU ld links the data segment immediately after the text segment, so there's no space left for the PHDR. I fix this by relocating and realigning the data segment.

The kernel loader requires `file offset % align == memory address % align`. Additionally, the kernel requires segments to be multiple of the minimum page size. On hugepage kernels, that's 2MB.

All of this together means when I move the data segment to make space for the PHDR, it needs to be realigned to 2MB, so it becomes huge.

**Comment by lunixbochs** [comment] 2017-03-28 16:49
Can you try again on latest master?

**Comment by mehQQ** [comment] 2017-03-28 17:01
It seems working properly and the patched size shrinks to 27KB. This really solved my problem. Thanks for the rapid reply, really appreciate it. And sorry for the duplicating.

**Comment by lunixbochs** [comment] 2017-03-28 17:12
Thanks! I'd love to hear your thoughts on patchkit.

I'm also working on another project that will hopefully allow me to really revamp the compiler/linker stuff soon.

**Closed by lunixbochs** 2017-03-28 17:12 UTC
